"""Regression tests for the encrypted credential store (Tier 0 item 0.3, Phase B).

Covers:
1. ``_Vault`` -- Fernet at-rest encryption, env-key vs 0600-keyfile resolution,
   loud plaintext fallback when ``cryptography`` is absent, fail-open decrypt for
   legacy/wrong-key reads.
2. ``CredentialStore`` -- in-memory plaintext / on-disk ciphertext round-trip,
   ``confirm_credential`` as the *only* path to ``confirmed=True``, dedup, and
   legacy plaintext files still loading.
3. The ``cred_store_add/get/list/confirm`` MCP tools end-to-end -- the on-disk
   vault holds ciphertext, the audit log never holds the cleartext secret, and
   ``confirmed`` only flips via the deliberate confirm call.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Any

import pytest
from cryptography.fernet import Fernet

from tools.credential_store import CredentialRecord, CredentialStore, _Vault

_CLEARTEXT = "super-secret-password-42!"
_NTLM = "aad3b435b51404eeaad3b435b51404ee"


def _rec(
    username: str = "admin",
    password: str = _CLEARTEXT,
    ctype: str = "password",
    target_host: str = "10.0.0.50",
    confirmed: bool = False,
) -> CredentialRecord:
    return CredentialRecord(
        timestamp=time.time(),
        source_host="10.0.0.50",
        target_host=target_host,
        username=username,
        password=password,
        credential_type=ctype,
        source_action="test",
        confirmed=confirmed,
    )


# ── 1. _Vault ───────────────────────────────────────────────────────────────


def test_vault_env_key_roundtrip(monkeypatch, tmp_path):
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    v = _Vault(tmp_path)
    assert v.enabled is True
    token = v.encrypt(_CLEARTEXT)
    assert token != _CLEARTEXT
    assert token.startswith("gAAAAA")  # Fernet token prefix
    assert v.decrypt(token) == _CLEARTEXT


def test_vault_keyfile_autogenerated(monkeypatch, tmp_path):
    """The keyfile is auto-generated OUTSIDE the workspace tree (0600), so the
    AI's unrestricted workspace reads can never reach it."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    vault_dir = tmp_path / "vault_home"
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(vault_dir))
    store_dir = tmp_path / "workspace"
    v = _Vault(store_dir)
    assert v.enabled is True
    assert (store_dir / ".vault_key").exists() is False  # never in-workspace
    assert v._keyfile.parent == vault_dir
    assert v._keyfile.exists()
    import os as _os

    assert oct(v._keyfile.stat().st_mode & 0o777) == "0o600"
    token = v.encrypt(_CLEARTEXT)
    assert v.decrypt(token) == _CLEARTEXT


def test_vault_legacy_in_workspace_keyfile_adopted(monkeypatch, tmp_path):
    """A legacy in-workspace ``.vault_key`` is moved out (not copied) so old
    stores keep decrypting and no key material stays AI-readable."""
    from tools.credential_store import _vault_key_path

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    vault_dir = tmp_path / "vault_home"
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(vault_dir))
    store_dir = tmp_path / "workspace"
    store_dir.mkdir(parents=True)
    legacy = store_dir / ".vault_key"
    legacy.write_text("legacy-key-material", encoding="utf-8")
    v = _Vault(store_dir)
    assert v._keyfile == _vault_key_path(store_dir)
    assert v._keyfile.exists()
    assert v._keyfile.read_text(encoding="utf-8").strip() == "legacy-key-material"
    assert not legacy.exists()  # moved, not copied


def test_vault_plaintext_fallback_when_cryptography_missing(monkeypatch, tmp_path):
    """When cryptography can't import, the vault disables loudly and stores plaintext."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    _Vault._plaintext_warned = False  # reset the one-time warning gate
    # Force `from cryptography.fernet import Fernet` inside _Vault.__init__ to fail.
    real = sys.modules.get("cryptography.fernet")
    sys.modules["cryptography.fernet"] = None  # sentinel -> ImportError on submodule import
    try:
        v = _Vault(tmp_path)
        assert v.enabled is False
        assert v.encrypt(_CLEARTEXT) == _CLEARTEXT  # passthrough
        assert v.decrypt("anything") == "anything"  # passthrough
    finally:
        if real is None:
            sys.modules.pop("cryptography.fernet", None)
        else:
            sys.modules["cryptography.fernet"] = real
    assert _Vault._plaintext_warned is True


def test_vault_decrypt_failopen_on_wrong_key(monkeypatch, tmp_path):
    key_a = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_a)
    va = _Vault(tmp_path)
    token = va.encrypt(_CLEARTEXT)
    # A different key cannot decrypt -- the vault returns the token unchanged
    # rather than raising (legacy/wrong-key reads never brick the store).
    key_b = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_b)
    vb = _Vault(tmp_path)
    assert vb.enabled is True
    assert vb.decrypt(token) == token  # fail-open, not an exception


# ── 2. CredentialStore ──────────────────────────────────────────────────────


def test_store_writes_ciphertext_disk_memory_plaintext(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    assert store.encryption_enabled is True
    store.add(_rec(password=_CLEARTEXT))

    # In memory: plaintext
    assert store.all_credentials()[0].password == _CLEARTEXT
    # On disk: ciphertext -- the cleartext never appears in the file bytes
    disk = (tmp_path / "credentials.jsonl").read_text(encoding="utf-8")
    assert _CLEARTEXT not in disk
    line = json.loads(disk.strip().splitlines()[-1])
    assert line["password"].startswith("gAAAAA")
    assert line["confirmed"] is False  # add stores unconfirmed


def test_store_reloads_plaintext_from_ciphertext(monkeypatch, tmp_path):
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    s1 = CredentialStore(tmp_path)
    s1.add(_rec(password=_CLEARTEXT))
    # New instance, same key -> decrypts back to plaintext
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].password == _CLEARTEXT


def test_store_legacy_plaintext_file_still_loads(monkeypatch, tmp_path):
    """A pre-encryption plaintext file must still load (fail-open decrypt)."""
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    (tmp_path / "credentials.jsonl").write_text(
        json.dumps(
            {
                "timestamp": time.time(),
                "source_host": "10.0.0.50",
                "target_host": "10.0.0.50",
                "username": "legacy",
                "password": _CLEARTEXT,  # plaintext, not a Fernet token
                "credential_type": "password",
                "source_action": "legacy",
                "confirmed": False,
                "notes": "",
            }
        )
        + "\n",
        encoding="utf-8",
    )
    store = CredentialStore(tmp_path)
    recs = store.all_credentials()
    assert len(recs) == 1
    # decrypt() returns the value unchanged when it isn't a valid token
    assert recs[0].password == _CLEARTEXT


def test_confirm_credential_is_only_path_to_confirmed(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    assert store.all_credentials()[0].confirmed is False

    # confirm without validated=True is refused by the gate -- flips nothing
    assert store.confirm_credential(username="admin", target_host="10.0.0.50") is False
    assert store.all_credentials()[0].confirmed is False
    # confirm with validated=True flips it
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
    assert store.all_credentials()[0].confirmed is True
    # re-confirm of already-confirmed returns False (no new confirmation)
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is False
    # confirm of a non-existent cred returns False
    assert store.confirm_credential(username="nobody", target_host="10.0.0.50", validated=True) is False
    # confirm persisted to disk (encrypted + HMAC-signed) and reloads confirmed
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is True


def test_confirm_credential_filtered_by_type(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="svc", password=_CLEARTEXT, ctype="password"))
    store.add(_rec(username="svc", password=_NTLM, ctype="hash"))
    # confirm only the hash, not the password
    assert (
        store.confirm_credential(username="svc", target_host="10.0.0.50", credential_type="hash", validated=True)
        is True
    )
    pw, h = sorted(store.all_credentials(), key=lambda r: r.credential_type)
    assert pw.credential_type == "hash" and pw.confirmed is True
    assert h.credential_type == "password" and h.confirmed is False


def test_add_dedups_same_username_host_type(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50", ctype="password"))
    store.add(_rec(username="admin", target_host="10.0.0.50", ctype="password"))
    assert len(store.all_credentials()) == 1
    # different type -> separate record
    store.add(_rec(username="admin", target_host="10.0.0.50", ctype="hash"))
    assert len(store.all_credentials()) == 2


def test_save_rewrites_all_encrypted(monkeypatch, tmp_path):
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    store = CredentialStore(tmp_path)
    store.add(_rec(username="a", password="pwA"))
    store.add(_rec(username="b", password="pwB"))
    store.confirm_credential(username="a", target_host="10.0.0.50", validated=True)  # triggers save()
    disk = (tmp_path / "credentials.jsonl").read_text(encoding="utf-8")
    assert "pwA" not in disk and "pwB" not in disk  # all ciphertext
    assert disk.count("gAAAAA") == 2


# ── 3. MCP cred_store tools end-to-end ───────────────────────────────────────


def _make_server(tmp_path: Path, *, require_allowlist: bool = False):
    from mcp_exploit_server import create_mcp_server
    from tools.cve_lookup import CVESearchSettings, NVDClient
    from tools.exploit_search import ExploitSearch, ExploitSearchSettings
    from tools.web_researcher import WebResearcher, WebResearcherSettings

    config: dict[str, Any] = {"exploit": {"require_explicit_allowlist": require_allowlist, "allowed_targets": []}}
    return create_mcp_server(
        ExploitSearch(ExploitSearchSettings()),
        NVDClient(CVESearchSettings()),
        WebResearcher(WebResearcherSettings()),
        tmp_path,
        config,
    )


def _text(result) -> str:
    content = result[0] if isinstance(result, (list, tuple)) else result
    if hasattr(content, "content"):
        content = content.content
    return "".join(getattr(c, "text", str(c)) for c in content)


@pytest.mark.asyncio
async def test_mcp_cred_store_add_encrypts_and_audits_redacted(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    text = _text(
        await mcp.call_tool(
            "cred_store_add",
            {
                "target_ip": "10.0.0.50",
                "username": "admin",
                "password": _CLEARTEXT,
                "credential_type": "password",
            },
        )
    )
    assert "CRED_STORE_ADD: stored" in text
    assert "ENCRYPTION_AT_REST: ENABLED" in text

    # On-disk vault is ciphertext
    cred_file = tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl"
    assert cred_file.exists()
    disk = cred_file.read_text(encoding="utf-8")
    assert _CLEARTEXT not in disk

    # Audit log args redacted (password never reaches exploit_audit.jsonl)
    audit = (tmp_path / "exploit_audit.jsonl").read_text(encoding="utf-8")
    assert _CLEARTEXT not in audit
    assert "***REDACTED***" in audit


@pytest.mark.asyncio
async def test_mcp_cred_store_add_rejects_bad_inputs(tmp_path):
    mcp = _make_server(tmp_path)
    # bad target_ip -> ERROR (invalid target)
    assert "Invalid" in _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "999.0.0.50", "username": "u", "password": "p"})
    )
    # missing username
    assert "BLOCKED" in _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "", "password": "p"})
    )
    # missing secret
    assert "BLOCKED" in _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "u", "password": ""})
    )
    # bad type
    assert "BLOCKED" in _text(
        await mcp.call_tool(
            "cred_store_add", {"target_ip": "10.0.0.50", "username": "u", "password": "p", "credential_type": "raw"}
        )
    )


@pytest.mark.asyncio
async def test_mcp_cred_store_get_masks_then_reveals(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})

    # default get masks the secret
    masked = _text(await mcp.call_tool("cred_store_get", {"target_ip": "10.0.0.50", "username": "admin"}))
    assert "admin" in masked
    assert _CLEARTEXT not in masked
    assert "masked" in masked.lower()

    # include_secret reveals it
    revealed = _text(
        await mcp.call_tool("cred_store_get", {"target_ip": "10.0.0.50", "username": "admin", "include_secret": True})
    )
    assert _CLEARTEXT in revealed


@pytest.mark.asyncio
async def test_mcp_cred_store_list_safe_no_cleartext(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    listed = _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    assert "admin" in listed
    assert "confirmed=False" in listed
    assert _CLEARTEXT not in listed  # safe summary


@pytest.mark.asyncio
async def test_mcp_cred_store_confirm_flips_confirmed(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    # before: unconfirmed
    assert "confirmed=False" in _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    # confirm without validated=True is refused (the gate) -- flips nothing
    refused = _text(await mcp.call_tool("cred_store_confirm", {"target_ip": "10.0.0.50", "username": "admin"}))
    assert "validation required" in refused.lower()
    assert "confirmed=False" in _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    # confirm with validated=True flips it
    conf = _text(
        await mcp.call_tool("cred_store_confirm", {"target_ip": "10.0.0.50", "username": "admin", "validated": True})
    )
    assert "confirmed=True" in conf
    # after: confirmed
    listed = _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    assert "confirmed=True" in listed
    # confirm of a non-existent cred (validated) -> not found
    miss = _text(
        await mcp.call_tool("cred_store_confirm", {"target_ip": "10.0.0.50", "username": "ghost", "validated": True})
    )
    assert "no unconfirmed matching" in miss


@pytest.mark.asyncio
async def test_mcp_cred_store_add_duplicate_not_readded(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    second = _text(
        await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    )
    assert "duplicate" in second.lower()
    listed = _text(await mcp.call_tool("cred_store_list", {"target_ip": "10.0.0.50"}))
    assert listed.count("admin/password") == 1


# ── 4. HMAC integrity + validated gate (Tier 0 item 0.3, Unit E) ─────────────
#
# ``confirmed=True`` is the trust gate for credential reuse. Two defenses pin it:
# (1) ``confirm_credential`` refuses without ``validated=True``, so a careless or
#     harvest-time call cannot promote an unvalidated credential; (2) the
#     ``confirmed`` flag is HMAC-signed at rest, so a hand-edited file, a file
#     copied from another workspace, or anything written under plaintext fallback
#     cannot carry a forged ``confirmed=True`` into memory -- it is downgraded to
#     False on load and logged.


def test_confirm_refused_without_validated_flag(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    # bare confirm flips nothing and persists nothing
    assert store.confirm_credential(username="admin", target_host="10.0.0.50") is False
    assert store.all_credentials()[0].confirmed is False
    disk = (tmp_path / "credentials.jsonl").read_text(encoding="utf-8")
    assert json.loads(disk.strip().splitlines()[-1])["confirmed"] is False


def test_hmac_confirmed_survives_reload_same_key(monkeypatch, tmp_path):
    """A signed confirmed=True reloads confirmed under the same vault key."""
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
    line = json.loads((tmp_path / "credentials.jsonl").read_text(encoding="utf-8").strip().splitlines()[-1])
    assert "sig" in line and line["sig"]  # on-disk record carries an HMAC
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is True  # sig verifies -> survives


def test_hmac_tampered_confirmed_downgraded(monkeypatch, tmp_path):
    """A hand-edited confirmed=True with no HMAC is downgraded on load -- a forged
    confirmed flag is never trusted."""
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    store_path = tmp_path / "credentials.jsonl"
    rec_line = json.loads(store_path.read_text(encoding="utf-8").strip().splitlines()[-1])
    rec_line["confirmed"] = True
    rec_line.pop("sig", None)  # strip the signature -> unauthenticated
    store_path.write_text(json.dumps(rec_line) + "\n", encoding="utf-8")
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is False  # downgraded, not trusted


def test_hmac_flipped_confirmed_breaks_signature(monkeypatch, tmp_path):
    """Flipping confirmed=True on a signed record (leaving the stale sig) makes the
    signature not verify under the key -> downgraded. Tamper-evidence holds even
    when the attacker knows to keep a sig field."""
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key)
    store = CredentialStore(tmp_path)
    store.add(_rec(username="admin", target_host="10.0.0.50"))
    store_path = tmp_path / "credentials.jsonl"
    rec_line = json.loads(store_path.read_text(encoding="utf-8").strip().splitlines()[-1])
    rec_line["confirmed"] = True  # flip the flag, KEEP the (now-stale) sig
    store_path.write_text(json.dumps(rec_line) + "\n", encoding="utf-8")
    s2 = CredentialStore(tmp_path)
    assert s2.all_credentials()[0].confirmed is False  # sig no longer matches


def test_hmac_foreign_workspace_confirmed_downgraded(monkeypatch, tmp_path):
    """A confirmed=True signed under a different vault key is downgraded when read
    under this workspace's key (the file was copied in from elsewhere)."""
    key_a = Fernet.generate_key().decode()
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", key_a)
    store_a = CredentialStore(tmp_path)
    store_a.add(_rec(username="admin", target_host="10.0.0.50"))
    assert store_a.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
    # read the same on-disk file under a DIFFERENT key -> sig does not verify
    monkeypatch.setenv("AI_NMAP_VAULT_KEY", Fernet.generate_key().decode())
    store_b = CredentialStore(tmp_path)
    assert store_b.all_credentials()[0].confirmed is False


def test_plaintext_fallback_confirmed_never_trusted_from_disk(monkeypatch, tmp_path):
    """In plaintext-fallback mode no HMAC can be produced, so a confirmed=True on
    disk is never trusted and is downgraded on reload -- only a SIGNED confirmed
    survives. (The in-memory confirm still works; the gate is the reload.)"""
    _Vault._plaintext_warned = False
    real = sys.modules.get("cryptography.fernet")
    sys.modules["cryptography.fernet"] = None  # force ImportError inside _Vault
    try:
        store = CredentialStore(tmp_path)
        assert store.encryption_enabled is False
        store.add(_rec(username="admin", target_host="10.0.0.50"))
        # the validated gate still flips the in-memory flag
        assert store.confirm_credential(username="admin", target_host="10.0.0.50", validated=True) is True
        assert store.all_credentials()[0].confirmed is True
        # but no sig could be written, so a reload must not trust confirmed=True
        s2 = CredentialStore(tmp_path)
        assert s2.all_credentials()[0].confirmed is False
    finally:
        if real is None:
            sys.modules.pop("cryptography.fernet", None)
        else:
            sys.modules["cryptography.fernet"] = real


# ── 5. Workspace read/list denylist for credential artifacts (Unit E) ────────


def _read_audit(workspace: Path) -> list[dict[str, Any]]:
    audit = workspace / "exploit_audit.jsonl"
    if not audit.exists():
        return []
    return [json.loads(line) for line in audit.read_text(encoding="utf-8").splitlines() if line.strip()]


@pytest.mark.asyncio
async def test_read_workspace_file_denies_vault_keyfile(monkeypatch, tmp_path):
    """The vault keyfile is deny-listed from workspace reads: serving it would
    hand the credential-store Fernet key to the model (ciphertext = plaintext).
    The live key lives outside the workspace tree; a legacy in-workspace path
    is refused by basename either way."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(tmp_path / "vault_home"))
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    # no key material under the workspace tree anymore
    assert not (tmp_path / "credentials" / "10.0.0.50" / ".vault_key").exists()
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "credentials/10.0.0.50/.vault_key"}))
    assert out.startswith("BLOCKED:")
    # ... however the key path is spelled
    out2 = _text(await mcp.call_tool("read_workspace_file", {"filename": ".vault_key"}))
    assert out2.startswith("BLOCKED:")


@pytest.mark.asyncio
async def test_read_workspace_file_reads_credentials_store_lab(monkeypatch, tmp_path):
    """LAB BUILD: the ciphertext credential store is readable (the sensitive-credential
    denylist was removed). The cleartext password is encrypted at rest, so it is not
    present in the returned ciphertext."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    assert (tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl").exists()
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "credentials/10.0.0.50/credentials.jsonl"}))
    assert "BLOCKED" not in out  # no longer refused
    assert _CLEARTEXT not in out  # cleartext is encrypted at rest
    assert "gAAAAA" in out  # the ciphertext IS returned (unrestricted)


@pytest.mark.asyncio
async def test_list_workspace_shows_credentials_subtree_lab(monkeypatch, tmp_path):
    """LAB BUILD: the credentials/ subtree is no longer hidden -- list_workspace
    shows it (operator-box filesystem is unrestricted)."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    listed = _text(await mcp.call_tool("list_workspace", {}))
    assert "credentials" in listed.lower()  # subtree is shown
    assert ".vault_key" not in listed  # keyfile names are never listed
    assert "credentials.jsonl" in listed


@pytest.mark.asyncio
async def test_read_workspace_file_is_audited(monkeypatch, tmp_path):
    """Every read_workspace_file call writes an audit record (traceability)."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    (tmp_path / "scan.txt").write_text("nmap output", encoding="utf-8")
    await mcp.call_tool("read_workspace_file", {"filename": "scan.txt"})
    audit = _read_audit(tmp_path)
    rr = [r for r in audit if r["tool_name"] == "read_workspace_file"]
    assert rr and any(r["status"] == "completed" for r in rr)
    assert rr[0]["args"]["filename"] == "scan.txt"  # filename logged, not secret


@pytest.mark.asyncio
async def test_read_workspace_file_still_reads_normal_files(monkeypatch, tmp_path):
    """The denylist must not block legitimate workspace files (regression guard)."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    (tmp_path / "loot.txt").write_text("here is some loot", encoding="utf-8")
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "loot.txt"}))
    assert "here is some loot" in out


# ── 6. Unit E bypass hardening (confirmed-forge, hardlink alias, link-list leak) ─


def test_add_forces_confirmed_false_even_when_caller_supplies_true(
    monkeypatch,
    tmp_path,
    caplog,
):
    """Bypass 1 (validated-gate forge): ``add`` must not persist a caller-supplied
    ``confirmed=True``. Without this, a harvest path (or a hand-built record) could
    store a confirmed credential that reloads HMAC-verified -- silently bypassing
    the ``confirm_credential(validated=True)`` gate the exploit loop trusts before
    reusing a credential at full access. The *only* path to confirmed=True stays
    ``confirm_credential``; ``add`` is the harvester and must yield unconfirmed."""
    import logging

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    store = CredentialStore(tmp_path)
    rec = _rec(username="admin", target_host="10.0.0.50", confirmed=True)
    with caplog.at_level(logging.WARNING, logger="tools.credential_store"):
        store.add(rec)
    # the record object itself is forced back to unconfirmed before it is stored
    assert rec.confirmed is False
    assert store.all_credentials()[0].confirmed is False
    # on-disk: confirmed=False, so the HMAC we just wrote covers False (not True)
    line = json.loads((tmp_path / "credentials.jsonl").read_text(encoding="utf-8").strip().splitlines()[-1])
    assert line["confirmed"] is False
    assert "sig" in line and line["sig"]
    # reload: verified signature + confirmed=False -> stays False (no promotion
    # from a forge; only confirm_credential(validated=True) can flip this)
    store2 = CredentialStore(tmp_path)
    assert store2.all_credentials()[0].confirmed is False
    # the forge attempt was not silent -- the operator-visible warning fired
    assert any("forcing False" in r.message for r in caplog.records)


@pytest.mark.asyncio
async def test_cred_store_add_notes_secret_redacted_in_audit(monkeypatch, tmp_path):
    """Bypass 6 (free-text leak): a secret placed in the free-text ``notes`` param
    must not reach ``exploit_audit.jsonl`` in cleartext. ``notes`` mirrors
    ``input_text`` -- free text the LLM can stuff with anything, and
    ``_mask_secret_content`` only catches known inline-credential *shapes*, so the
    whole value is wholesale-redacted in the audit log (execution still uses the raw
    value). The on-disk store is operator-controlled; the audit log is the leak
    surface this closes."""
    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    secret = "plaintext-is-hunter2-from-notes"
    text = _text(
        await mcp.call_tool(
            "cred_store_add",
            {
                "target_ip": "10.0.0.50",
                "username": "admin",
                "password": _CLEARTEXT,
                "credential_type": "password",
                "notes": f"reused from ssh login; {secret}",
            },
        )
    )
    assert "CRED_STORE_ADD: stored" in text
    audit = (tmp_path / "exploit_audit.jsonl").read_text(encoding="utf-8")
    assert secret not in audit  # the notes-embedded secret never reaches disk
    assert _CLEARTEXT not in audit  # the password arg is also redacted
    # the notes field is masked wholesale (not shape-matched); password too
    records = _read_audit(tmp_path)
    add_recs = [r for r in records if r.get("tool_name") == "cred_store_add"]
    assert add_recs
    assert all(r["args"].get("notes") == "***REDACTED***" for r in add_recs)
    assert all(r["args"].get("password") == "***REDACTED***" for r in add_recs)


@pytest.mark.asyncio
async def test_read_workspace_file_hardlink_to_store_readable_key_out_of_tree(monkeypatch, tmp_path):
    """A benign-named hard link to the ciphertext store stays readable, but
    the keyfile no longer lives under the workspace tree at all — there is
    no in-workspace key to link to."""
    import os

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    monkeypatch.setenv("BREACHPILOT_VAULT_DIR", str(tmp_path / "vault_home"))
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    cred_file = tmp_path / "credentials" / "10.0.0.50" / "credentials.jsonl"
    assert cred_file.exists()
    assert not (tmp_path / "credentials" / "10.0.0.50" / ".vault_key").exists()
    cred_link = tmp_path / "loot.txt"
    try:
        os.link(cred_file, cred_link)
    except OSError as exc:  # filesystem does not support hard links
        pytest.skip(f"hard links unavailable on this filesystem: {exc!r}")
    assert os.path.samefile(cred_link, cred_file)
    # the credentials-store hard-link is read back (ciphertext returned)
    out = _text(await mcp.call_tool("read_workspace_file", {"filename": "loot.txt"}))
    assert "BLOCKED" not in out
    assert _CLEARTEXT not in out  # cleartext is encrypted at rest
    assert "gAAAAA" in out  # the ciphertext IS returned (unrestricted)


@pytest.mark.asyncio
async def test_list_workspace_shows_credentials_via_link_alias_lab(monkeypatch, tmp_path):
    """LAB BUILD: the credentials/ subtree is shown (nothing is hidden). A symlink
    alias is NOT followed (os.walk followlinks=False), so only the real credentials/
    subtree is enumerated -- but it IS shown (the lab build does not hide it)."""
    import os
    import subprocess

    monkeypatch.delenv("AI_NMAP_VAULT_KEY", raising=False)
    mcp = _make_server(tmp_path)
    await mcp.call_tool("cred_store_add", {"target_ip": "10.0.0.50", "username": "admin", "password": _CLEARTEXT})
    cred_dir = tmp_path / "credentials"
    alias = tmp_path / "data"
    # try a real symlink first (POSIX always; Windows needs dev-mode/privilege)
    created = False
    try:
        os.symlink(cred_dir, alias, target_is_directory=True)
        created = True
    except (OSError, NotImplementedError):
        created = False
    # Windows junction via mklink /J needs no privilege
    if not created and os.name == "nt":
        try:
            r = subprocess.run(
                ["cmd", "/c", "mklink", "/J", str(alias), str(cred_dir)],
                capture_output=True,
                timeout=10,
            )
            created = r.returncode == 0
        except Exception:
            created = False
    if not created:
        pytest.skip("link/junction creation unavailable in this environment")
    listed = _text(await mcp.call_tool("list_workspace", {}))
    low = listed.lower()
    # the real credentials/ subtree is shown (the lab build does not hide it)
    assert "credentials" in low
    assert ".vault_key" not in listed  # keyfile names are never listed
    assert "credentials.jsonl" in listed
