"""Regenerate docs/skills/catalog.md from skills/*/SKILL.md frontmatter.

Stdlib only (re, no yaml dependency). Regex-parses the YAML frontmatter
(name/description/domain/subdomain/tags/version) of every SKILL.md under
skills/ (top level + skills/maybe/) and emits a catalog grouped by domain
plus one alphabetical table. Counts are computed live at generation time.

Usage (from repo root):
    python scripts/generate_skill_catalog.py
"""

from __future__ import annotations

import datetime
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
DOC = REPO / "docs" / "skills" / "catalog.md"

FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*(?:\n|$)", re.S)
KEY_RE = re.compile(r"^[A-Za-z0-9_-]+:")


def _single(fm: str, key: str) -> str:
    m = re.search(rf"(?m)^{re.escape(key)}:\s*(.+?)\s*$", fm)
    if not m:
        return ""
    return m.group(1).strip().strip("'\"").strip()


def _description(fm: str) -> str:
    m = re.search(r"(?m)^description:\s*(.*)$", fm)
    if not m:
        return ""
    lines = [m.group(1)]
    for ln in fm[m.end():].splitlines():
        if ln.strip() == "" or ln[:1] in (" ", "\t"):
            lines.append(ln)
        elif KEY_RE.match(ln):
            break
        else:
            break
    text = "\n".join(lines).strip()
    if len(text) >= 2 and text[0] == text[-1] and text[0] in ("'", '"'):
        text = text[1:-1]
    return " ".join(text.split())


def _tags(fm: str) -> list[str]:
    m = re.search(r"(?m)^tags:\s*(.*)$", fm)
    if not m:
        return []
    inline = m.group(1).strip()
    if inline.startswith("["):
        return [t.strip().strip("'\"") for t in inline.strip("[]").split(",") if t.strip()]
    if inline:
        return [inline.strip().strip("'\"")]
    tags: list[str] = []
    for ln in fm[m.end():].splitlines():
        item = re.match(r"^\s*-\s*(.+?)\s*$", ln)
        if item:
            tags.append(item.group(1).strip().strip("'\""))
        elif ln.strip() == "":
            continue
        elif KEY_RE.match(ln):
            break
        else:
            break
    return tags


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


class Skill:
    def __init__(self, path: Path):
        self.path = path
        self.dir = path.parent.name
        self.maybe = "maybe" in path.relative_to(SKILLS).parts
        m = FM_RE.match(path.read_text(encoding="utf-8", errors="replace"))
        fm = m.group(1) if m else ""
        self.name = _single(fm, "name") or self.dir
        self.description = _description(fm)
        self.domain = _single(fm, "domain") or "(none)"
        self.subdomain = _single(fm, "subdomain") or "(none)"
        self.tags = _tags(fm)
        self.version = _single(fm, "version") or "(none)"


def short(desc: str, limit: int = 160) -> str:
    if len(desc) <= limit:
        return desc
    cut = desc[:limit].rsplit(" ", 1)[0]
    return cut + "…"


def main() -> int:
    files = sorted(SKILLS.glob("**/SKILL.md"))
    skills = [Skill(p) for p in files]
    skills.sort(key=lambda s: s.name.lower())
    today = datetime.date.today().isoformat()

    by_domain: dict[str, list[Skill]] = {}
    for s in skills:
        by_domain.setdefault(s.domain, []).append(s)
    n_maybe = sum(1 for s in skills if s.maybe)

    out = [
        "---",
        "title: Skill Catalog (Generated)",
        "description: Every runtime skill — name, domain, version, tags. Grouped by domain plus an alphabetical table.",
        "source: [skills/*/SKILL.md]",
        f"generated: {today}",
        f"skills: {len(skills)}",
        "---",
        "",
        "# Skill Catalog (Generated)",
        "",
        f"> Auto-generated by `scripts/generate_skill_catalog.py` — do not edit by hand. "
        f"{len(skills)} skills ({len(skills) - n_maybe} top-level + {n_maybe} `maybe/` tier) as of {today}.",
        "",
        "## Counts",
        "",
        f"- **Total: {len(skills)}**",
    ]
    for domain in sorted(by_domain):
        out.append(f"- `{domain}`: {len(by_domain[domain])}")
    out += ["", "## By domain", ""]
    for domain in sorted(by_domain):
        group = by_domain[domain]
        out.append(f"### {domain} ({len(group)})")
        out.append("")
        for s in group:
            maybe = " `maybe/`" if s.maybe else ""
            out.append(
                f"- **{s.name}**{maybe} — {_cell(short(s.description))} "
                f"(`{s.subdomain}`, v{s.version})"
            )
        out.append("")
    out += [
        "## All skills (alphabetical)",
        "",
        "| Name | Domain | Subdomain | Version | Tags |",
        "|------|--------|-----------|---------|------|",
    ]
    for s in skills:
        out.append(
            f"| `{s.name}` | `{s.domain}` | `{s.subdomain}` | `{s.version}` "
            f"| {_cell(', '.join(s.tags)) or '—'} |"
        )
    out.append("")
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text("\n".join(out), encoding="utf-8")
    missing = [s.dir for s in skills if not s.name or not s.description or s.domain == "(none)"]
    print(f"skills: {len(skills)} ({len(skills) - n_maybe} top-level + {n_maybe} maybe/)")
    print(f"domains: {{{', '.join(f'{d}: {len(g)}' for d, g in sorted(by_domain.items()))}}}")
    if missing:
        print(f"WARNING: incomplete frontmatter in: {missing}")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
