"""Type-debt baseline gate: fail CI when mypy debt grows.

Runs mypy over ``tools/`` with NO ``disable_error_code`` suppressions and
compares the result against the checked-in ``mypy-baseline.txt`` (total +
per-file error counts). The gate fails when:

- the total error count increases, or
- any file's error count increases (including files not in the baseline —
  new debt in a previously clean file fails immediately).

Paying debt down is always allowed: when a subsystem is fixed, refresh the
baseline with ``python scripts/mypy_debt.py --update`` (which rewrites
``mypy-baseline.txt`` from the current run) and commit both the fixes and
the new baseline together. Never hand-edit the baseline upward.

Migration strategy (documented in ``docs/type-checking.md``): graduate
subsystems to strict per-module overrides in ``pyproject.toml`` in this
order — ``tools/kernel`` → ``tools/api`` → ``tools/sandbox`` →
orchestration/session code → remaining modules — restoring ``arg-type``,
``return-value``, ``assignment``, ``union-attr``, ``call-arg``,
``operator``, ``index``, ``list-item``, ``name-defined`` and
``no-untyped-def`` as each tier goes clean. New code must not use bare
``Any`` to silence the gate; prefer TypedDict/dataclasses/Protocols and
explicit Optional types.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "mypy-baseline.txt"

_ERROR_RE = re.compile(r"^(\S+?):\d+:.*?error:")

# A mypy run with zero suppressions: same scope/flags as CI's permissive
# check, minus every disable. Written to a temp config (NOT pyproject) so
# the measurement is hermetic: per-module strict overrides in pyproject are
# intentionally not loaded here — this pass measures raw debt with one fixed
# python_version, reproducible on any interpreter.
_INLINE_CONFIG = """\
[mypy]
python_version = 3.12
warn_return_any = false
ignore_missing_imports = true
show_error_codes = true
"""


def run_mypy() -> tuple[dict[str, int], int, str]:
    """Run the unsuppressed mypy pass. Returns (per-file counts, total, raw output)."""
    import tempfile

    with tempfile.NamedTemporaryFile(mode="w", suffix=".ini", delete=False) as tmp:
        tmp.write(_INLINE_CONFIG)
        config_path = tmp.name
    try:
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "mypy",
                "--config-file",
                config_path,
                "--follow-imports=skip",
                "--no-error-summary",
                "--show-error-codes",
                "tools",
            ],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=570,
        )
    finally:
        Path(config_path).unlink(missing_ok=True)
    counts: dict[str, int] = {}
    for line in (proc.stdout + proc.stderr).splitlines():
        match = _ERROR_RE.match(line)
        if match:
            counts[match.group(1)] = counts.get(match.group(1), 0) + 1
    return counts, sum(counts.values()), proc.stdout + proc.stderr


def load_baseline() -> tuple[dict[str, int], int]:
    counts: dict[str, int] = {}
    total = 0
    with BASELINE_PATH.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("total:"):
                total = int(line.split(":", 1)[1].strip())
                continue
            parts = line.split()
            counts[parts[0]] = int(parts[1])
    return counts, total


def write_baseline(counts: dict[str, int]) -> None:
    lines = [
        "# mypy type-debt baseline — see scripts/mypy_debt.py and docs/type-checking.md.",
        "# Generated by `python scripts/mypy_debt.py --update`. Never hand-edit upward.",
        f"total: {sum(counts.values())}",
    ]
    lines.extend(f"{path} {counts[path]}" for path in sorted(counts))
    BASELINE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    counts, total, _raw = run_mypy()
    if "--update" in argv:
        write_baseline(counts)
        print(f"baseline rewritten: {total} errors in {len(counts)} files")
        return 0
    base_counts, base_total = load_baseline()
    failures: list[str] = []
    if total > base_total:
        failures.append(f"total type errors grew: baseline {base_total} -> current {total}")
    for path in sorted(set(counts) | set(base_counts)):
        old = base_counts.get(path, 0)
        new = counts.get(path, 0)
        if new > old:
            failures.append(f"{path}: {old} -> {new} errors")
    if failures:
        print("mypy type-debt gate FAILED (new debt is rejected; fix it or pay down the file):")
        for failure in failures:
            print(f"  - {failure}")
        print("See docs/type-checking.md. To refresh after paying debt down: python scripts/mypy_debt.py --update")
        return 1
    improved = base_total - total
    print(f"mypy type-debt gate passed: {total} errors (baseline {base_total}, delta {-improved:+d})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
